/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package students;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Nzuki
 */
public class Add_Student extends javax.swing.JFrame {
    Statement st;
ResultSet rs;
Connection conn;
dbconnect con;
PreparedStatement pst;

            String driver="org.postgresql.Driver";
            String url="jdbc:postgresql://localhost:5432/postgres";
            String username="postgres";
            String password="awesome";

    /**
     * Creates new form Add_Student
     */
    public Add_Student() throws Exception {
        initComponents();
        con=new dbconnect();
       st= con.getConnection().createStatement();
       int average = 0;
        int sum = 0;
        
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
         
        
        
     
 
        try{
               
                Class.forName(driver);
                conn=DriverManager.getConnection(url, username, password);
               
                

                String sql="select * from student ORDER BY marks ASC" ;
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();

                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                model=(DefaultTableModel)jTable1.getModel();
                
                for(int i=0; i<jTable1.getRowCount(); i++){
         int sum1=Integer.parseInt(jTable1.getValueAt(i, 2).toString());
            sum=sum+sum1;
            
         }
                model.addRow(new Object[]{"","TOTAL", sum});
                for(int i=0; i<jTable1.getRowCount(); i++){
         int sum1m=Integer.parseInt(jTable1.getValueAt((jTable1.getRowCount()-1), 2).toString());
           
            int avg = sum1m/(jTable1.getRowCount()-1);
            average = avg;
         }
         
       
        
        model.addRow(new Object[]{"","AVERAGE", average});
        
                
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sname = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        marks = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        Edit = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        reg = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));
        jPanel4.setForeground(new java.awt.Color(0, 51, 51));
        jPanel4.setToolTipText("");
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, -20, -1, -1));

        jLabel50.setBackground(new java.awt.Color(255, 255, 255));
        jLabel50.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("STUDENTS");
        jPanel4.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 380, 80));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 90));

        jLabel10.setBackground(new java.awt.Color(0, 51, 51));
        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 51));
        jLabel10.setText("Student Name");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 110, -1));

        sname.setToolTipText("");
        sname.setBorder(null);
        sname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                snameKeyTyped(evt);
            }
        });
        jPanel1.add(sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 230, 20));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 240, 10));

        jLabel2.setBackground(new java.awt.Color(0, 51, 51));
        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Marks");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 80, -1));

        marks.setToolTipText("");
        marks.setBorder(null);
        marks.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                marksKeyTyped(evt);
            }
        });
        jPanel1.add(marks, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 230, 20));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 240, 10));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Edit.setBackground(new java.awt.Color(255, 255, 255));
        Edit.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Edit.setForeground(new java.awt.Color(0, 51, 51));
        Edit.setText("Update");
        Edit.setInheritsPopupMenu(true);
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        jPanel2.add(Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 90, 30));

        jButton15.setBackground(new java.awt.Color(255, 255, 255));
        jButton15.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton15.setForeground(new java.awt.Color(0, 51, 51));
        jButton15.setText("Delete");
        jButton15.setInheritsPopupMenu(true);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 90, 30));

        jButton16.setBackground(new java.awt.Color(255, 255, 255));
        jButton16.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton16.setForeground(new java.awt.Color(0, 51, 51));
        jButton16.setText("Clear");
        jButton16.setInheritsPopupMenu(true);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 90, 30));

        jButton17.setBackground(new java.awt.Color(255, 255, 255));
        jButton17.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton17.setForeground(new java.awt.Color(0, 51, 51));
        jButton17.setText("Save");
        jButton17.setInheritsPopupMenu(true);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 260, 110));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, 200));

        jLabel3.setBackground(new java.awt.Color(0, 51, 51));
        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Registration Number");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 170, -1));

        reg.setToolTipText("");
        reg.setBorder(null);
        reg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                regKeyTyped(evt);
            }
        });
        jPanel1.add(reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 230, 20));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 240, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void snameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_snameKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_snameKeyTyped

    private void marksKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_marksKeyTyped
        // TODO add your handling code here:

        
    }//GEN-LAST:event_marksKeyTyped

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        // TODO add your handling code here:
        try
            {
                Class.forName(driver);
                conn=DriverManager.getConnection(url, username, password);
              
                String sql="update student set student_name=?,marks=? where registration_number=?";
               

                pst=conn.prepareStatement(sql);

                
                pst.setString(1, sname.getText());
                pst.setString(2, marks.getText());
                pst.setString(3, reg.getText());
               
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Updated");
                int average = 0;
        int sum = 0;
        
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
         
        
        
     
 
        try{
               
                Class.forName(driver);
                conn=DriverManager.getConnection(url, username, password);
               
                

                String sq="select * from student ORDER BY marks ASC" ;
                pst=conn.prepareStatement(sq);
                rs=pst.executeQuery();

                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                model=(DefaultTableModel)jTable1.getModel();
                
                for(int i=0; i<jTable1.getRowCount(); i++){
         int sum1=Integer.parseInt(jTable1.getValueAt(i, 2).toString());
            sum=sum+sum1;
            
         }
                model.addRow(new Object[]{"","TOTAL", sum});
                for(int i=0; i<jTable1.getRowCount(); i++){
         int sum1m=Integer.parseInt(jTable1.getValueAt((jTable1.getRowCount()-1), 2).toString());
           
            int avg = sum1m/(jTable1.getRowCount()-1);
            average = avg;
         }
         
       
        
        model.addRow(new Object[]{"","AVERAGE", average});
        
                
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
            
        }
                
                } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
            
        }
       
    }//GEN-LAST:event_EditActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        try
            {
                Class.forName(driver);
                conn=DriverManager.getConnection(url, username, password);
                
                String sql="delete from student where registration_number=?";

                pst=conn.prepareStatement(sql);

                pst.setString(1, reg.getText());
                int input=JOptionPane.showConfirmDialog(null, "Are you sure you want to delete the selected record?", "DELETE",JOptionPane.YES_NO_OPTION);
                if(input==JOptionPane.YES_OPTION){

                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Data Deleted!");
                    int average = 0;
        int sum = 0;
        
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
         
        
        
     
 
        try{
               
                Class.forName(driver);
                conn=DriverManager.getConnection(url, username, password);
               
                

                String sq="select * from student ORDER BY marks ASC" ;
                pst=conn.prepareStatement(sq);
                rs=pst.executeQuery();

                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                model=(DefaultTableModel)jTable1.getModel();
                
                for(int i=0; i<jTable1.getRowCount(); i++){
         int sum1=Integer.parseInt(jTable1.getValueAt(i, 2).toString());
            sum=sum+sum1;
            
         }
                model.addRow(new Object[]{"","TOTAL", sum});
                for(int i=0; i<jTable1.getRowCount(); i++){
         int sum1m=Integer.parseInt(jTable1.getValueAt((jTable1.getRowCount()-1), 2).toString());
           
            int avg = sum1m/(jTable1.getRowCount()-1);
            average = avg;
         }
         
       
        
        model.addRow(new Object[]{"","AVERAGE", average});
        
                
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
            
        }
                    
                   } 
            }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
            
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
       sname.setText("");
       marks.setText("");
       reg.setText("");
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        
        try{
                        Class.forName(driver);
                conn=DriverManager.getConnection(url, username, password);
                        String sq="insert into student (registration_number, student_name, marks) values (?,?,?)";
                        pst=conn.prepareStatement(sq);
                       
                        pst.setString(1, reg.getText());
                        pst.setString(2, sname.getText());
                        pst.setString(3, marks.getText());
                        pst.execute();
                        JOptionPane.showMessageDialog(null, "Data Saved");
                        //jTable1.setDefaultEditor(Object.class, null);
        int average = 0;
        int sum = 0;
        
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
         
        
        
     
 
        try{
               
                Class.forName(driver);
                conn=DriverManager.getConnection(url, username, password);
               
                

                String sql="select * from student ORDER BY marks ASC" ;
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();

                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                model=(DefaultTableModel)jTable1.getModel();
                
                for(int i=0; i<jTable1.getRowCount(); i++){
         int sum1=Integer.parseInt(jTable1.getValueAt(i, 2).toString());
            sum=sum+sum1;
            
         }
                model.addRow(new Object[]{"","TOTAL", sum});
                for(int i=0; i<jTable1.getRowCount(); i++){
         int sum1m=Integer.parseInt(jTable1.getValueAt((jTable1.getRowCount()-1), 2).toString());
           
            int avg = sum1m/(jTable1.getRowCount()-1);
            average = avg;
         }
         
       
        
        model.addRow(new Object[]{"","AVERAGE", average});
        
                
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
            
        }
                    }catch(Exception e){
                      JOptionPane.showMessageDialog(null, e);

                    }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void regKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_regKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_regKeyTyped

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        int selectedRowIndex = jTable1.getSelectedRow();
        String regi = (String)model.getValueAt(selectedRowIndex, 0);
        String mark = (String)model.getValueAt(selectedRowIndex, 2);
        String nam = (String)model.getValueAt(selectedRowIndex, 1);
        reg.setText(regi);
        marks.setText(mark);
        sname.setText(nam);
        
        
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Add_Student().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Add_Student.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Edit;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField marks;
    private javax.swing.JTextField reg;
    private javax.swing.JTextField sname;
    // End of variables declaration//GEN-END:variables
}
